#!/usr/bin/env bash
# Copy the design-system files used by the i2c.pl page into docs/ds/.
# GitHub Pages publishes only docs/, so the page cannot load design-system/ directly.
# Run after every change in design-system/ and commit the result.
#
# i2c.css is copied without its Google Fonts @import: the page self-hosts Mulish
# (docs/fonts/), so visitors' browsers send no requests to Google.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$root/design-system"
dest="$root/docs/ds"

rm -rf "$dest"
mkdir -p "$dest/assets/Logos" "$dest/assets/Web"

cp "$src/tokens.css" "$dest/tokens.css"
{
  echo "/* Generated by scripts/sync-design-system.sh from design-system/i2c.css. Do not edit. */"
  sed '/^@import .*fonts\.googleapis\.com/d' "$src/i2c.css"
} > "$dest/i2c.css"
if grep -q 'fonts\.googleapis\.com' "$dest/i2c.css"; then
  echo "error: docs/ds/i2c.css still references Google Fonts; update the filter in $0" >&2
  exit 1
fi

cp "$src/assets/Logos/i2c-lockup-black.svg" "$dest/assets/Logos/"
for file in favicon-i2c.svg favicon-i2c-32.png apple-touch-icon-i2c-180.png og-i2c-1200x630.png; do
  cp "$src/assets/Web/$file" "$dest/assets/Web/"
done

echo "Synced design-system/ -> docs/ds/"
